alias cat='ccat'
alias edit='$=EDITOR'
alias bashconfig='$=EDITOR $HOME/.bashrc'
alias zshconfig='$=EDITOR $HOME/.zshrc'
alias ohmyzsh='$=EDITOR $HOME/.oh-my-zsh'
alias ohmybash='$=EDITOR $HOME/.oh-my-bash'
